name: ci
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code download
        uses: actions/checkout@v4
      - name: build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
